### ISSUE TITLE
ReactiveETL.Infrastructure.SqlCommandSet build error

### ISSUE THREAD

**Issue by Martin-DC** [madhon/ReactiveETL#2]
I seems that this file has some error, I can't build it
such as 
public void Dispose() => doDispose();
my vs2013 and net4.5 can't use it

**Comment by madhon** [comment]
This is due to it using a C# 6 feature in the code which 2013 dosnt support, you will need to install/use vs2015 to build.

**Comment by Martin-DC** [comment]
Thanks




发自网易邮箱大师
On 04/19/2017 17:56, Madhon wrote:

This is due to it using a C# 6 feature in the code which 2013 dosnt support, you will need to install/use vs2015 to build.
